apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/minio-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args:
          - server
          - /data
          - --console-address
          - ":9002"
        ports:
          - name: api
            containerPort: 9000
          - name: console
            containerPort: 9002
        env:
          - name: MINIO_ACCESS_KEY
            value: "fakesecret"
          - name: MINIO_SECRET_KEY
            value: "fakesecret"
        volumeMounts:
          - mountPath: /data
            name: minio-storage
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  echo "Waiting for MinIO to be ready..."
                  until mc alias set local http://127.0.0.1:9000 fakesecret fakesecret; do
                    echo "MinIO not ready, retrying..."
                    sleep 2
                  done
                  echo "MinIO Ready! Creating single bucket..."
                  mc mb -p local/local-datalake
                  echo "Creating folders with dummy files..."
                  touch dummyfile
                  mc cp dummyfile local/local-datalake/warehouse/dummyfile
                  echo "Datalake folder structure created!"
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30000
    - name: console
      port: 9002
      targetPort: 9002
      nodePort: 30002
  selector:
    app: minio
