apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-work-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-jupyter-combined
  labels:
    app: spark-jupyter-combined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-jupyter-combined
  template:
    metadata:
      labels:
        app: spark-jupyter-combined
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: spark-jupyter
        image: spark-jupyter-iceberg:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 7077   # Spark Master
          - containerPort: 8080   # Spark Master UI
          - containerPort: 4040   # Spark App UI
          - containerPort: 8888   # Jupyter Notebook
        env:
          - name: AWS_ACCESS_KEY_ID
            value: fakesecret
          - name: AWS_SECRET_ACCESS_KEY
            value: fakesecret
          - name: AWS_REGION
            value: us-east-1
        volumeMounts:
        - name: local-work
          mountPath: /home/jovyan/work
        args:
        - /bin/sh
        - -c
        - |
          /usr/local/spark/sbin/start-master.sh && \
          /usr/local/spark/sbin/start-worker.sh spark://localhost:7077 && \
          start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
      volumes:
      - name: local-work
        persistentVolumeClaim:
          claimName: spark-work-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spark-jupyter-service
spec:
  selector:
    app: spark-jupyter-combined
  type: NodePort
  ports:
    - name: master
      protocol: TCP
      port: 7077
      targetPort: 7077
      nodePort: 30077
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: app-ui
      protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30440
    - name: jupyter
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30888
