apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-standalone
  labels:
    app: spark-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-standalone
  template:
    metadata:
      labels:
        app: spark-standalone
    spec:
      securityContext:
        runAsUser: 0   # <<< Run as root (for local, dev only)
      containers:
      - name: spark-standalone
        image: apache/spark-py:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7077
        - containerPort: 8080
        - containerPort: 4040
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /opt/spark/logs && \
            chmod 777 /opt/spark/logs && \
            /opt/spark/sbin/start-master.sh && \
            tail -f /dev/null
