apiVersion: v1
kind: Service
metadata:
  name: spark-standalone
spec:
  selector:
    app: spark-standalone
  ports:
    - name: master
      protocol: TCP
      port: 7077
      targetPort: 7077
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: app-ui
      protocol: TCP
      port: 4040
      targetPort: 4040
  type: NodePort
